### ISSUE TITLE
Images not present in WinForm Screen Shots

### ISSUE THREAD

**Issue by Jason-MacDonald** [Jason-MacDonald/SDV701-Project#2]
**Location:**
Wiki - Application Screen Shots (WinForm Application)

**Issue:**
No image functionality or display indicated in Screen Shot documentation. 

**Suggested Fix:**
Update screenshots to include images and upload functionality.

**Additional Notes:**
May not be a project requirement as is not explicitly mentioned. Need to confirm requirement as images were discussed in class.

**Comment by MatthiasNZ** [comment]
I hope I understand this "Issue" correctly?!

I see you have an image column/field in the db design, so it would be nice to have it in the screenshots also (for consistency with the ERD) even though that wasn't explicitly asked for, for stage 1.

**Comment by Jason-MacDonald** [comment]
> I hope I understand this "Issue" correctly?!
> 
> I see you have an image column/field in the db design, so it would be nice to have it in the screenshots also (for consistency with the ERD) even though that wasn't explicitly asked for, for stage 1.

No problem, this "**issue**" was mainly to test out automation of issues through the git hub project board, essentially just a TODO.

**Comment by Jason-MacDonald** [comment]
[Screenshots](https://github.com/Jason-MacDonald/SDV701-Project/wiki/Screen-Shots) have been updated to include images and indicate upload functionality.
