### ISSUE TITLE
Inheritance in DB schema

### ISSUE THREAD

**Issue by MatthiasNZ** [Jason-MacDonald/SDV701-Project#3]
Not sure if this is the right place, I'm somewhat of a _late adopter_ of GitHub ;-)

I see your sub-types as separate entities in the diagram.  Is this a logical or physical (implementation) dgm?  If physical, i.e. you have 3 tables, that is fine, and an added "bonus" point, i.e. an "ORM other than TPH".  You're only required to do one, and you already have the image/media field as the "additional feature/technology".  You're welcome to do both, I just want to protect you from doing more work than expected.

I will talk a bit about the different ORM patterns in a class session soon.

As for having a super-class/entity _Item_, this is certainly a good idea for a future-proof application, but I wouldn't do it in the context of this assignment for the same reason as above.

**Comment by Jason-MacDonald** [comment]
> Not sure if this is the right place, I'm somewhat of a _late adopter_ of GitHub ;-)

This is the perfect place! 👍 Gives me a chance to see how everything works. 
 
> I see your sub-types as separate entities in the diagram. Is this a logical or physical (implementation) dgm? If physical, i.e. you have 3 tables, that is fine, and an added "bonus" point, i.e. an "ORM other than TPH". You're only required to do one, and you already have the image/media field as the "additional feature/technology". You're welcome to do both, I just want to protect you from doing more work than expected.

I have created a new issue for my selected solution [here](https://github.com/Jason-MacDonald/SDV701-Project/issues/4).

I will be collapsing the database hierarchy as I feel the image feature is more important for an application of this type and the database is a lesser concern for this project.

> As for having a super-class/entity _Item_, this is certainly a good idea for a future-proof application, but I wouldn't do it in the context of this assignment for the same reason as above.

No problem, I had assumed this would be the case. It just hurts me inside every time I look at the diagram. 😭
