### ISSUE TITLE
Multiple Additional Features

### ISSUE THREAD

**Issue by Jason-MacDonald** [Jason-MacDonald/SDV701-Project#4]
**Location:**
Wiki - Database Schema

**Issue:**
Multiple additional features in documentation where only one is required.
1. Object Relational Mapping (ORM): Table Per Type (TPT), and
2. Images

**Suggested Fix:**

- Select **Images** as the additional feature.

- **Collapse Hierarchy:** Table Per Hierarchy (TPH): Use one table in the database for all bikes. Use null-able fields for unnecessary data. 

- Update Wiki to reflect changes.

**Additional Notes:**
Images would generally be required for an application of this type and The database is not the main focus for this project. 

**Related Issues:** [Images not present in WinForm Screen Shots](https://github.com/Jason-MacDonald/SDV701-Project/issues/2)

**Comment by Jason-MacDonald** [comment]
The **ERD Bike Hierarchy** has been collapsed and the [Wiki ERD](https://github.com/Jason-MacDonald/SDV701-Project/wiki/Database-Schema) has been updated to reflect the changes.

**Comment by MatthiasNZ** [comment]
Well, functionally, you're right, an application like this would benefit most from including images into the app.  Wearing my system architect's hat, ORMs are an architectural feature, and as such rich pickings for a course such as ours.  In this case, however, moving from TPH to TPT makes the db more complex, but OO-programming (possibly) a bit simpler.  So I like your conclusion based on recognition that this is not really about db design.  But, as often, I'm really sitting on the fence on this one :-)
